"""Σ1 -> Σ2 reference-predication models and builders."""

from .interface import (
    ReferencePredicationInterface,
    Sigma2InterfaceResult,
)
from .models import (
    CaseImpactVector2,
    EgoReferenceMode,
    GeneralityLevel,
    GrammaticalFactorGI,
    GrammaticalRole,
    LegacySigma1ReferenceUnit,
    MentalFactor,
    OntologyClass,
    PositionalPotential,
    PredicationType,
    PropositionConstraintVector,
    PropositionMode,
    RatioVector,
    ReferencePredicationVector2,
    SentenceSpace,
    Sigma1PrerequisiteReport,
    Sigma1ReferenceUnit,
    Sigma1Thresholds,
    Sigma2Builder,
    SigmaCompatibilityAdapter,
    Sigma2Matrix,
    SigmaPrerequisiteChecker,
    SigmaTransitionError,
    TypePotential,
)
from .thresholds import (
    ReferencePredicationThresholdBundle,
    THRESHOLD_BUNDLE_V1,
)

__all__ = [
    "CaseImpactVector2",
    "EgoReferenceMode",
    "GeneralityLevel",
    "GrammaticalFactorGI",
    "GrammaticalRole",
    "LegacySigma1ReferenceUnit",
    "MentalFactor",
    "OntologyClass",
    "PositionalPotential",
    "PredicationType",
    "PropositionConstraintVector",
    "PropositionMode",
    "RatioVector",
    "ReferencePredicationVector2",
    "SentenceSpace",
    "Sigma1PrerequisiteReport",
    "Sigma1ReferenceUnit",
    "Sigma1Thresholds",
    "Sigma2InterfaceResult",
    "Sigma2Builder",
    "ReferencePredicationInterface",
    "SigmaCompatibilityAdapter",
    "Sigma2Matrix",
    "SigmaPrerequisiteChecker",
    "SigmaTransitionError",
    "TypePotential",
    "ReferencePredicationThresholdBundle",
    "THRESHOLD_BUNDLE_V1",
]
